/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p.i;

import Modal.Cliente;
import dao.ClienteDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class TelaCadastroConsultaCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroConsultaCliente
     */
    public TelaCadastroConsultaCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        pnlGuias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        txtEstado = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnAdicionar = new javax.swing.JButton();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        lblMensagem = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtCPF = new javax.swing.JTextField();
        jdcData = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultaCliente = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtBuscaCPF = new javax.swing.JTextField();
        txtBuscaNome = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblMensagemBusca = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbSexoAtualiza = new javax.swing.JComboBox<>();
        txtEmailAtualiza = new javax.swing.JTextField();
        txtCPFAtualiza = new javax.swing.JTextField();
        txtNomeAtualiza = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEstadoAtualiza = new javax.swing.JTextField();
        txtCidadeAtualiza = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTelefoneAtualiza = new javax.swing.JFormattedTextField();
        cbEstadoCivilAtualiza = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jdcDataAtualiza = new com.toedter.calendar.JDateChooser();
        Atualizar = new javax.swing.JButton();
        btnCancelarBusca = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblErroAtualiza = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        txtNome.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNome.setName(""); // NOI18N
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        jLabel3.setText("E-Mail");

        txtEmail.setMaximumSize(new java.awt.Dimension(64, 22));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        jLabel4.setText("Sexo");

        jLabel6.setText("Estado");

        jLabel7.setText("Cidade");

        jLabel8.setText("Telefone");

        jLabel9.setText("Estado civíl");

        jLabel10.setText("Data de nascimento");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        cbSexo.setMaximumSize(new java.awt.Dimension(89, 22));
        cbSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbSexoFocusLost(evt);
            }
        });

        txtEstado.setMaximumSize(new java.awt.Dimension(64, 22));

        txtCidade.setMaximumSize(new java.awt.Dimension(64, 22));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setMaximumSize(new java.awt.Dimension(64, 22));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viúvo(a)" }));
        cbEstadoCivil.setMaximumSize(new java.awt.Dimension(105, 22));
        cbEstadoCivil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbEstadoCivilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbEstadoCivilFocusLost(evt);
            }
        });

        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFKeyTyped(evt);
            }
        });

        jdcData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdcDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdcDataFocusLost(evt);
            }
        });
        jdcData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdcDataKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(124, 124, 124)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEstadoCivil, 0, 152, Short.MAX_VALUE)
                            .addComponent(jdcData, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pnlGuias.addTab("Cadastrar Cliente", jPanel1);

        tblConsultaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "E-Mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultaCliente);
        if (tblConsultaCliente.getColumnModel().getColumnCount() > 0) {
            tblConsultaCliente.getColumnModel().getColumn(0).setResizable(false);
            tblConsultaCliente.getColumnModel().getColumn(1).setResizable(false);
            tblConsultaCliente.getColumnModel().getColumn(2).setResizable(false);
            tblConsultaCliente.getColumnModel().getColumn(3).setResizable(false);
            tblConsultaCliente.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel11.setText("CPF");

        jLabel12.setText("Nome");

        txtBuscaCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaCPFKeyTyped(evt);
            }
        });

        txtBuscaNome.setMaximumSize(new java.awt.Dimension(64, 22));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar/Visualizar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblMensagemBusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addComponent(lblMensagemBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBuscaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagemBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlGuias.addTab("Consultar Cliente", jPanel2);

        jLabel13.setText("Nome");

        jLabel14.setText("CPF");

        jLabel15.setText("E-Mail");

        jLabel16.setText("Sexo");

        cbSexoAtualiza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        cbSexoAtualiza.setMaximumSize(new java.awt.Dimension(89, 22));
        cbSexoAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbSexoAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbSexoAtualizaFocusLost(evt);
            }
        });

        txtEmailAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));
        txtEmailAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailAtualizaFocusLost(evt);
            }
        });

        txtCPFAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFAtualizaFocusLost(evt);
            }
        });
        txtCPFAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFAtualizaActionPerformed(evt);
            }
        });
        txtCPFAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFAtualizaKeyTyped(evt);
            }
        });

        txtNomeAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNomeAtualiza.setName(""); // NOI18N
        txtNomeAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeAtualizaFocusLost(evt);
            }
        });
        txtNomeAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAtualizaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeAtualizaKeyTyped(evt);
            }
        });

        jLabel17.setText("Estado");

        txtEstadoAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));

        txtCidadeAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel18.setText("Cidade");

        jLabel19.setText("Telefone");

        try {
            txtTelefoneAtualiza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));

        cbEstadoCivilAtualiza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viúvo(a)" }));
        cbEstadoCivilAtualiza.setMaximumSize(new java.awt.Dimension(105, 22));
        cbEstadoCivilAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbEstadoCivilAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbEstadoCivilAtualizaFocusLost(evt);
            }
        });

        jLabel20.setText("Estado civíl");

        jLabel21.setText("Data de nascimento");

        jdcDataAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdcDataAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdcDataAtualizaFocusLost(evt);
            }
        });
        jdcDataAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdcDataAtualizaKeyTyped(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        btnCancelarBusca.setText("Cancelar");
        btnCancelarBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBuscaActionPerformed(evt);
            }
        });

        jLabel22.setText("ID");

        lblId.setText("0");

        lblErroAtualiza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnCancelarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(cbSexoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtCPFAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEstadoCivilAtualiza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCidadeAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefoneAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcDataAtualiza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(txtEstadoAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblErroAtualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErroAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstadoCivilAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcDataAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pnlGuias.addTab("Atualizar/Visualizar Cliente", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped

        char c= evt.getKeyChar();
        
        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }
        
        if(txtNome.getText().length()>50){
            evt.consume();
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

        txtNome.setText(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        txtNome.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        txtEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        String nome=txtNome.getText();
        String cpf=txtCPF.getText();
        String email=txtEmail.getText();
        Date nascimento=jdcData.getDate();
        String sexo = cbSexo.getSelectedItem().toString();
        String estado=txtEstado.getText();
        String cidade=txtCidade.getText();
        String telefone=txtTelefone.getText();
        String estadoCivil =cbEstadoCivil.getSelectedItem().toString();
      
        if(nome.length()==0 || txtCPF.getText().length()!=11 || email.length()==0 || jdcData.getDate()==null || sexo.equals("Selecione") || estadoCivil.equals("Selecione")){
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("Por favor, preencha todos os campos mínimos necessários");
           
            if(txtNome.getText().length()==0){
                txtNome.setBackground(Color.RED);
            }
            
            if(txtCPF.getText().length()!=11){
                txtCPF.setBackground(Color.RED);
            }
            
            if(txtEmail.getText().length()==0){
                txtEmail.setBackground(Color.RED);
            }
            
            if(jdcData.getDate()==null){
                jdcData.setBackground(Color.RED);
            }
            
            if(sexo.equals("Selecione")){
                cbSexo.setBackground(Color.red);
            }
            
            if(estadoCivil.equals("Selecione")){
                cbEstadoCivil.setBackground(Color.red);
            }
            
        }else{
            jdcData.setBackground(Color.WHITE);
            lblMensagem.setForeground(Color.BLACK);
            lblMensagem.setText(" ");
            
            Cliente obj = new Cliente (nome, email, sexo, estado, cidade, estadoCivil, nascimento, telefone, cpf);
            
           
            boolean salvo= ClienteDAO.salvar(obj);
            if(salvo){
            JOptionPane.showMessageDialog(this, "Cliente adicionado com sucesso");
            }else{
            JOptionPane.showMessageDialog(rootPane, "Falha!");
        }
            
            
            txtCPF.setText("");
            txtNome.setText("");
            txtCidade.setText("");
            txtEmail.setText("");
            txtEstado.setText("");
            txtNome.setText("");
            txtTelefone.setText("");
            cbSexo.setSelectedIndex(0);
            cbEstadoCivil.setSelectedIndex(0);
            jdcData.setCalendar(null);
            
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        lblMensagem.setForeground(Color.BLACK);
        lblMensagem.setText(" ");
        
        txtCPF.setText("");
        txtNome.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEstado.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        cbSexo.setSelectedIndex(0);
        cbEstadoCivil.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpf = txtBuscaCPF.getText();
        String nome = txtBuscaNome.getText();
        
        if(cpf.isBlank()==true&&nome.isBlank()==true){
            ArrayList<Cliente> lista = dao.ClienteDAO.Listar();

            DefaultTableModel modelo = (DefaultTableModel)tblConsultaCliente.getModel();
            modelo.setRowCount(0);
            for(Cliente item : lista){
                modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getEmail()), String.valueOf(item.getTelefone()) });
            }
        }else{
            if(cpf.isBlank()==true&&nome.isBlank()==false){
                ArrayList<Cliente> lista = dao.ClienteDAO.Listar(nome);

                DefaultTableModel modelo = (DefaultTableModel)tblConsultaCliente.getModel();
                modelo.setRowCount(0);
                for(Cliente item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getEmail()), String.valueOf(item.getTelefone()) });
                }
            }else{
                if(cpf.isBlank()==false&&nome.isBlank()==true){
                    ArrayList<Cliente> lista = dao.ClienteDAO.ListarCpf(cpf);

                    DefaultTableModel modelo = (DefaultTableModel)tblConsultaCliente.getModel();
                    modelo.setRowCount(0);
                    for(Cliente item : lista){
                        modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getEmail()), String.valueOf(item.getTelefone()) });
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscaCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaCPFKeyTyped
        char c= evt.getKeyChar();
        
        if( (c < '0' || c > '9')){
            evt.consume();
        }
        
        if(txtBuscaCPF.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtBuscaCPFKeyTyped

    private void cbSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoFocusGained
        cbSexo.setBackground(Color.yellow);
    }//GEN-LAST:event_cbSexoFocusGained

    private void cbSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoFocusLost
        cbSexo.setBackground(Color.white);
    }//GEN-LAST:event_cbSexoFocusLost

    private void cbEstadoCivilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbEstadoCivilFocusGained
        cbEstadoCivil.setBackground(Color.yellow);
    }//GEN-LAST:event_cbEstadoCivilFocusGained

    private void cbEstadoCivilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbEstadoCivilFocusLost
        cbEstadoCivil.setBackground(Color.white);
    }//GEN-LAST:event_cbEstadoCivilFocusLost

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setBackground(Color.yellow);
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        txtCPF.setBackground(Color.white);
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyTyped
        char c= evt.getKeyChar();
        
        if( (c < '0' || c > '9')){
            evt.consume();
        }
        
        if(txtCPF.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFKeyTyped

    private void jdcDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataFocusGained
        jdcData.setBackground(Color.yellow);
    }//GEN-LAST:event_jdcDataFocusGained

    private void jdcDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataFocusLost
        jdcData.setBackground(Color.WHITE);
        UIManager.put("textHighlight", Color.WHITE);
        UIManager.put("textHighlightText", Color.RED);
        UIManager.put("control", Color.GREEN);
    }//GEN-LAST:event_jdcDataFocusLost

    private void jdcDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcDataKeyTyped
        char c= evt.getKeyChar();
        
        if( (c < '0' || c > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jdcDataKeyTyped

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(tblConsultaCliente.getSelectedRow()<0){
            lblMensagemBusca.setText("Por favor selecione um cliente");
        }else{
            int linhaSelecionada = tblConsultaCliente.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel)tblConsultaCliente.getModel();

            int id = Integer.parseInt(tblConsultaCliente.getValueAt(linhaSelecionada, 0).toString());
            boolean retorno = dao.ClienteDAO.excluir(id);   
            if(retorno){
                modelo.removeRow(linhaSelecionada);
                JOptionPane.showMessageDialog(rootPane, "Excluída com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao excluír");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbSexoAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoAtualizaFocusGained
        cbSexoAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_cbSexoAtualizaFocusGained

    private void cbSexoAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoAtualizaFocusLost
        cbSexoAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_cbSexoAtualizaFocusLost

    private void txtEmailAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailAtualizaFocusGained
        txtEmailAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtEmailAtualizaFocusGained

    private void txtEmailAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailAtualizaFocusLost
        txtEmailAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtEmailAtualizaFocusLost

    private void txtCPFAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFAtualizaFocusGained
        txtCPFAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtCPFAtualizaFocusGained

    private void txtCPFAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFAtualizaFocusLost
        txtCPFAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtCPFAtualizaFocusLost

    private void txtCPFAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFAtualizaKeyTyped
        char c= evt.getKeyChar();
        
        if( (c < '0' || c > '9')){
            evt.consume();
        }
        
        if(txtCPFAtualiza.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFAtualizaKeyTyped

    private void txtNomeAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeAtualizaFocusGained
        txtNomeAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtNomeAtualizaFocusGained

    private void txtNomeAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeAtualizaFocusLost
        txtNomeAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNomeAtualizaFocusLost

    private void txtNomeAtualizaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAtualizaKeyReleased
        txtNomeAtualiza.setText(txtNomeAtualiza.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeAtualizaKeyReleased

    private void txtNomeAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAtualizaKeyTyped
        char c= evt.getKeyChar();
        
        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }
        
        if(txtNomeAtualiza.getText().length()>50){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeAtualizaKeyTyped

    private void cbEstadoCivilAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbEstadoCivilAtualizaFocusGained
        cbEstadoCivilAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_cbEstadoCivilAtualizaFocusGained

    private void cbEstadoCivilAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbEstadoCivilAtualizaFocusLost
        cbEstadoCivilAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_cbEstadoCivilAtualizaFocusLost

    private void jdcDataAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataAtualizaFocusGained
        jdcDataAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_jdcDataAtualizaFocusGained

    private void jdcDataAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataAtualizaFocusLost
        jdcDataAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_jdcDataAtualizaFocusLost

    private void jdcDataAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcDataAtualizaKeyTyped
        char c= evt.getKeyChar();
        
        if( (c < '0' || c > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jdcDataAtualizaKeyTyped

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed

        int id=Integer.parseInt(lblId.getText());
        
        String nome=txtNomeAtualiza.getText();
        String cpf=txtCPFAtualiza.getText();
        String email=txtEmailAtualiza.getText();
        Date nascimento=jdcDataAtualiza.getDate();
        String sexo = cbSexoAtualiza.getSelectedItem().toString();
        String estado=txtEstadoAtualiza.getText();
        String cidade=txtCidadeAtualiza.getText();
        String telefone=txtTelefoneAtualiza.getText();
        String estadoCivil =cbEstadoCivilAtualiza.getSelectedItem().toString();
        
        if(id!=0){
            if(nome.length()==0 || txtCPFAtualiza.getText().length()!=11 || email.length()==0 || jdcDataAtualiza.getDate()==null || sexo.equals("Selecione") || estadoCivil.equals("Selecione")){
            lblErroAtualiza.setForeground(Color.red);
            lblErroAtualiza.setText("Por favor, preencha todos os campos mínimos necessários");
           
            if(txtNomeAtualiza.getText().length()==0){
                txtNomeAtualiza.setBackground(Color.RED);
            }
            
            if(txtCPFAtualiza.getText().length()!=11){
                txtCPFAtualiza.setBackground(Color.RED);
            }
            
            if(txtEmailAtualiza.getText().length()==0){
                txtEmailAtualiza.setBackground(Color.RED);
            }
            
            if(jdcDataAtualiza.getDate()==null){
                jdcDataAtualiza.setBackground(Color.RED);
            }
            
            if(sexo.equals("Selecione")){
                cbSexoAtualiza.setBackground(Color.red);
            }
            
            if(estadoCivil.equals("Selecione")){
                cbEstadoCivilAtualiza.setBackground(Color.red);
            }
            
            }else{
                lblErroAtualiza.setText("");

                Cliente obj = new Cliente (nome, email, sexo, estado, cidade, estadoCivil, nascimento, telefone, cpf);

                boolean retorno = dao.ClienteDAO.atualizar(obj, id);   
                if(retorno){
                    JOptionPane.showMessageDialog(rootPane, "Atualizada com sucesso");
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Falha ao atualizar");
                }
            }
        }else{
            lblErroAtualiza.setForeground(Color.red);
            lblErroAtualiza.setText("Selecione um cliente para atualizar");
        }
        
    }//GEN-LAST:event_AtualizarActionPerformed

    private void btnCancelarBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBuscaActionPerformed
        Object[] options = { "Sim, cancelar", "Não, continuar" };
        int Cancelar = JOptionPane.showOptionDialog(null, "Cancelar a atualização?", "Confirmação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if (Cancelar==0){
            txtCPFAtualiza.setText("");
            txtCidadeAtualiza.setText("");
            txtEmailAtualiza.setText("");
            txtEstadoAtualiza.setText("");
            txtNomeAtualiza.setText("");
            txtTelefoneAtualiza.setText("");
            cbEstadoCivilAtualiza.setSelectedIndex(0);
            cbSexoAtualiza.setSelectedIndex(0);
            pnlGuias.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btnCancelarBuscaActionPerformed

    private void txtCPFAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFAtualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFAtualizaActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(tblConsultaCliente.getSelectedRow()<0){
                lblMensagemBusca.setText("Por favor selecione um cliente");
        }else{
            int linhaSelecionada = tblConsultaCliente.getSelectedRow();

            String id = tblConsultaCliente.getValueAt(linhaSelecionada, 0).toString();
            int ID =Integer.parseInt(id);

            ArrayList<Cliente> lista = dao.ClienteDAO.ListaAlterar(ID);

            for(Cliente item : lista){
                txtNomeAtualiza.setText(item.getNome());
                txtCPFAtualiza.setText(item.getCpf());
                txtEmailAtualiza.setText(item.getEmail());
                //sexo
                
                txtEstadoAtualiza.setText(item.getEstado());
                txtCidadeAtualiza.setText(item.getCidade());
                txtTelefoneAtualiza.setText(item.getTelefone());
                //EstadoCivil
                jdcDataAtualiza.setDate(item.getDataNascimento());
            }

            lblId.setText(id);
            pnlGuias.setSelectedIndex(2);
       }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarBusca;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbEstadoCivilAtualiza;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbSexoAtualiza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcData;
    private com.toedter.calendar.JDateChooser jdcDataAtualiza;
    private javax.swing.JLabel lblErroAtualiza;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagemBusca;
    private javax.swing.JTabbedPane pnlGuias;
    private javax.swing.JTable tblConsultaCliente;
    private javax.swing.JTextField txtBuscaCPF;
    private javax.swing.JTextField txtBuscaNome;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFAtualiza;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeAtualiza;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailAtualiza;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoAtualiza;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeAtualiza;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefoneAtualiza;
    // End of variables declaration//GEN-END:variables
}
