/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p.i;

import Modal.Produto;
import dao.ProdutoDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class TelaCadastroConsultaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProduto
     */
    public TelaCadastroConsultaProduto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGuias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdBusca = new javax.swing.JTextField();
        txtNomeBusca = new javax.swing.JTextField();
        lblMensagemBusca = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorMinBusca = new javax.swing.JTextField();
        txtValorMaxBusca = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        txtDescricaoProdutoAtualiza = new javax.swing.JTextField();
        txtValorProdutoAtualiza = new javax.swing.JTextField();
        txtNomeProdutoAtualiza = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtQuantidadeAtualiza = new javax.swing.JTextField();
        btnConfirmar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Nome");

        txtNomeProduto.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNomeProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeProdutoFocusLost(evt);
            }
        });
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });
        txtNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeProdutoKeyTyped(evt);
            }
        });

        jLabel3.setText("Valor");

        txtValorProduto.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValorProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorProdutoFocusLost(evt);
            }
        });
        txtValorProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorProdutoKeyTyped(evt);
            }
        });

        jLabel4.setText("Descrição");

        txtDescricaoProduto.setMaximumSize(new java.awt.Dimension(64, 22));
        txtDescricaoProduto.setName(""); // NOI18N
        txtDescricaoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescricaoProdutoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoProdutoFocusLost(evt);
            }
        });
        txtDescricaoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoProdutoKeyTyped(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel8.setText("Quantidade");

        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusLost(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)))
                .addGap(212, 212, 212))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pnlGuias.addTab("Cadastar Produto", jPanel1);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Descrição", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel5.setText("Nome");

        txtIdBusca.setMaximumSize(new java.awt.Dimension(64, 22));
        txtIdBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdBuscaKeyTyped(evt);
            }
        });

        txtNomeBusca.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNomeBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeBuscaKeyTyped(evt);
            }
        });

        lblMensagemBusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Valor Mínimo");

        jLabel7.setText("Valor Máximo");

        txtValorMinBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorMinBuscaKeyTyped(evt);
            }
        });

        txtValorMaxBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorMaxBuscaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblMensagemBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorMaxBusca))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorMinBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValorMinBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtValorMaxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblMensagemBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        pnlGuias.addTab("Consulta Produto", jPanel2);

        jLabel9.setText("Nome");

        jLabel10.setText("Valor");

        jLabel11.setText("Descrição");

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        txtDescricaoProdutoAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));
        txtDescricaoProdutoAtualiza.setName(""); // NOI18N
        txtDescricaoProdutoAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescricaoProdutoAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoProdutoAtualizaFocusLost(evt);
            }
        });
        txtDescricaoProdutoAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoProdutoAtualizaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoProdutoAtualizaKeyTyped(evt);
            }
        });

        txtValorProdutoAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValorProdutoAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorProdutoAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorProdutoAtualizaFocusLost(evt);
            }
        });
        txtValorProdutoAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorProdutoAtualizaKeyTyped(evt);
            }
        });

        txtNomeProdutoAtualiza.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNomeProdutoAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeProdutoAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeProdutoAtualizaFocusLost(evt);
            }
        });
        txtNomeProdutoAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoAtualizaActionPerformed(evt);
            }
        });
        txtNomeProdutoAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProdutoAtualizaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeProdutoAtualizaKeyTyped(evt);
            }
        });

        jLabel12.setText("Quantidade");

        txtQuantidadeAtualiza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantidadeAtualizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeAtualizaFocusLost(evt);
            }
        });
        txtQuantidadeAtualiza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeAtualizaKeyTyped(evt);
            }
        });

        btnConfirmar1.setText("Confirmar");
        btnConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmar1ActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        lblErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDescricaoProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValorProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(187, 187, 187))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNomeProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtQuantidadeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(139, 139, 139)))
                .addGap(23, 23, 23))
            .addComponent(lblErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(txtQuantidadeAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtValorProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDescricaoProdutoAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pnlGuias.addTab("Alterar/Adicionar produto", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoKeyTyped
        char c= evt.getKeyChar();

        if(txtDescricaoProduto.getText().length()>=30){
            evt.consume();
        }
    }//GEN-LAST:event_txtDescricaoProdutoKeyTyped

    private void txtValorProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorProdutoKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorProduto.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorProdutoKeyTyped

    private void txtNomeProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoKeyTyped
        char c= evt.getKeyChar();

        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }

        if(txtNomeProduto.getText().length()>20){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeProdutoKeyTyped

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(txtDescricaoProduto.getText().length() == 0 || txtNomeProduto.getText().length() == 0 || txtValorProduto.getText().length() == 0 || txtQuantidade.getText().length() == 0){
            
            if(txtNomeProduto.getText().length()==0){
                txtNomeProduto.setBackground(Color.RED);
            }
            
            if(txtDescricaoProduto.getText().length()==0){
                txtDescricaoProduto.setBackground(Color.RED);
            }
            
            if(txtValorProduto.getText().length()==0){
                txtValorProduto.setBackground(Color.RED);
            }
            
            if(txtQuantidade.getText().length()==0){
                txtQuantidade.setBackground(Color.RED);
            }
            
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("Por favor, preencha todos os campos");
            
        }else{
            lblMensagem.setText(" ");
            
            String nome = txtNomeProduto.getText();
            String descricao = txtDescricaoProduto.getText();
            double valor =Double.parseDouble(txtValorProduto.getText());
            int quantidade =Integer.parseInt(txtQuantidade.getText());
            
            Produto obj = new Produto (nome, descricao, valor, quantidade);
            
            boolean salvo= ProdutoDAO.Salvar(obj);
            if(salvo){
            JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso");
            }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao adicionar produto!");
            
            
            txtDescricaoProduto.setText("");
            txtNomeProduto.setText("");
            txtValorProduto.setText("");
            txtQuantidade.setText("");
        }
            }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtDescricaoProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoFocusGained
        txtDescricaoProduto.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtDescricaoProdutoFocusGained

    private void txtValorProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorProdutoFocusGained
        txtValorProduto.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtValorProdutoFocusGained

    private void txtNomeProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeProdutoFocusGained
        txtNomeProduto.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtNomeProdutoFocusGained

    private void txtDescricaoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoFocusLost
        txtDescricaoProduto.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDescricaoProdutoFocusLost

    private void txtValorProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorProdutoFocusLost
        txtValorProduto.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtValorProdutoFocusLost

    private void txtNomeProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeProdutoFocusLost
        txtNomeProduto.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNomeProdutoFocusLost

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtNomeProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoKeyReleased
        txtNomeProduto.setText(txtNomeProduto.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeProdutoKeyReleased

    private void txtDescricaoProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoKeyReleased
        txtDescricaoProduto.setText(txtDescricaoProduto.getText().toUpperCase());
    }//GEN-LAST:event_txtDescricaoProdutoKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtDescricaoProduto.setText("");
        txtNomeProduto.setText("");
        txtValorProduto.setText("");
        txtQuantidade.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if(tblProduto.getSelectedRow()<0){
                lblMensagemBusca.setText("Por favor selecione um cliente");
        }else{
            int linhaSelecionada = tblProduto.getSelectedRow();

            String id = tblProduto.getValueAt(linhaSelecionada, 0).toString();
            int ID =Integer.parseInt(id);

            ArrayList<Produto> lista = dao.ProdutoDAO.ListaAlterar(ID);

            for(Produto item : lista){
                txtNomeProdutoAtualiza.setText(item.getNome());
                txtDescricaoProdutoAtualiza.setText(item.getDescricao());
                txtQuantidadeAtualiza.setText(String.valueOf(item.getQuantidade()));
                txtValorProdutoAtualiza.setText(String.valueOf(item.getValor()));

            lblId.setText(id);
            pnlGuias.setSelectedIndex(2);
            }    
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nome=txtNomeBusca.getText();
        if(txtIdBusca.getText().length()==0 && txtValorMinBusca.getText().length()==0 && txtValorMaxBusca.getText().length()==0){
            ArrayList<Produto> lista = dao.ProdutoDAO.Listar(nome);

            DefaultTableModel modelo = (DefaultTableModel)tblProduto.getModel();
            modelo.setRowCount(0);
            for(Produto item : lista){
                modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getDescricao()), String.valueOf(item.getValor())});
            }
        }else{
            double valormax=Double.parseDouble(txtValorMaxBusca.getText());
            double valormin = Double.parseDouble(txtValorMinBusca.getText());
            int id=Integer.parseInt(txtIdBusca.getText());
            
            
            if(valormax!=0 && valormin!=0 && id!=0){
                ArrayList<Produto> lista = dao.ProdutoDAO.Listar(id, nome, valormax, valormin);

                DefaultTableModel modelo = (DefaultTableModel)tblProduto.getModel();
                modelo.setRowCount(0);
                for(Produto item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getDescricao()), String.valueOf(item.getValor())});
                }
            }else{
                if(valormax!=0 && valormin==0 && id==0){
                    ArrayList<Produto> lista = dao.ProdutoDAO.ListarValorMin(nome, valormin);

                    DefaultTableModel modelo = (DefaultTableModel)tblProduto.getModel();
                    modelo.setRowCount(0);
                    for(Produto item : lista){
                        modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getDescricao()), String.valueOf(item.getValor())});
                    }
                }else{
                    if(valormax==0 && valormin!=0 && id==0){
                        ArrayList<Produto> lista = dao.ProdutoDAO.ListarValorMax(nome, valormax);

                        DefaultTableModel modelo = (DefaultTableModel)tblProduto.getModel();
                        modelo.setRowCount(0);
                        for(Produto item : lista){
                            modelo.addRow(new String[]{String.valueOf(item.getId()), String.valueOf(item.getNome()), String.valueOf(item.getDescricao()), String.valueOf(item.getValor())});
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeBuscaKeyTyped
        char c= evt.getKeyChar();

        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }

        if(txtNomeBusca.getText().length()>20){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeBuscaKeyTyped

    private void txtValorMinBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorMinBuscaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorMinBusca.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorMinBuscaKeyTyped

    private void txtValorMaxBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorMaxBuscaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorMaxBusca.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorMaxBuscaKeyTyped

    private void txtIdBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdBuscaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtIdBusca.getText().length()>=5){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdBuscaKeyTyped

    private void txtQuantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusGained
        txtQuantidade.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtQuantidadeFocusGained

    private void txtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusLost
        txtQuantidade.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtQuantidadeFocusLost

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorProduto.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void txtDescricaoProdutoAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoAtualizaFocusGained
        txtDescricaoProdutoAtualiza.setBackground(Color.YELLOW);

    }//GEN-LAST:event_txtDescricaoProdutoAtualizaFocusGained

    private void txtDescricaoProdutoAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoAtualizaFocusLost
        txtDescricaoProdutoAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDescricaoProdutoAtualizaFocusLost

    private void txtDescricaoProdutoAtualizaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoAtualizaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdutoAtualizaKeyReleased

    private void txtDescricaoProdutoAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoProdutoAtualizaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdutoAtualizaKeyTyped

    private void txtValorProdutoAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorProdutoAtualizaFocusGained
        txtValorProdutoAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtValorProdutoAtualizaFocusGained

    private void txtValorProdutoAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorProdutoAtualizaFocusLost
        txtValorProdutoAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtValorProdutoAtualizaFocusLost

    private void txtValorProdutoAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorProdutoAtualizaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorProdutoAtualiza.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorProdutoAtualizaKeyTyped

    private void txtNomeProdutoAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeProdutoAtualizaFocusGained
        txtNomeProdutoAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtNomeProdutoAtualizaFocusGained

    private void txtNomeProdutoAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeProdutoAtualizaFocusLost
        txtNomeProdutoAtualiza.setBackground(Color.white);
    }//GEN-LAST:event_txtNomeProdutoAtualizaFocusLost

    private void txtNomeProdutoAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoAtualizaActionPerformed
    }//GEN-LAST:event_txtNomeProdutoAtualizaActionPerformed

    private void txtNomeProdutoAtualizaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoAtualizaKeyReleased
        txtNomeProdutoAtualiza.setText(txtNomeProdutoAtualiza.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeProdutoAtualizaKeyReleased

    private void txtNomeProdutoAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoAtualizaKeyTyped
        char c= evt.getKeyChar();

        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }

        if(txtNomeProdutoAtualiza.getText().length()>20){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeProdutoAtualizaKeyTyped

    private void txtQuantidadeAtualizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeAtualizaFocusGained
        txtQuantidadeAtualiza.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtQuantidadeAtualizaFocusGained

    private void txtQuantidadeAtualizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeAtualizaFocusLost
        txtQuantidadeAtualiza.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtQuantidadeAtualizaFocusLost

    private void txtQuantidadeAtualizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeAtualizaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtValorProdutoAtualiza.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantidadeAtualizaKeyTyped

    private void btnConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmar1ActionPerformed
        if(txtDescricaoProdutoAtualiza.getText().length() == 0 || txtNomeProdutoAtualiza.getText().length() == 0 || txtValorProdutoAtualiza.getText().length() == 0 || txtQuantidadeAtualiza.getText().length() == 0){
            
            if(txtNomeProdutoAtualiza.getText().length()==0){
                txtNomeProdutoAtualiza.setBackground(Color.RED);
            }
            
            if(txtDescricaoProdutoAtualiza.getText().length()==0){
                txtDescricaoProdutoAtualiza.setBackground(Color.RED);
            }
            
            if(txtValorProdutoAtualiza.getText().length()==0){
                txtValorProdutoAtualiza.setBackground(Color.RED);
            }
            
            if(txtQuantidadeAtualiza.getText().length()==0){
                txtQuantidadeAtualiza.setBackground(Color.RED);
            }
            
            lblErro.setForeground(Color.red);
            lblErro.setText("Por favor, preencha todos os campos");
            
        }else{
            lblErro.setText(" ");
            
            String nome = txtNomeProdutoAtualiza.getText();
            String descricao = txtDescricaoProdutoAtualiza.getText();
            double valor =Double.parseDouble(txtValorProdutoAtualiza.getText());
            int quantidade =Integer.parseInt(txtQuantidadeAtualiza.getText());
            int ID = Integer.parseInt(lblId.getText());
            
            Produto obj = new Produto (nome, descricao, valor, quantidade);
            
            boolean salvo= ProdutoDAO.Atualizar(nome, descricao, valor, quantidade, ID);
            if(salvo){
            JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso");
            }else{
            JOptionPane.showMessageDialog(rootPane, "Falha ao adicionar produto!");
            
            
            txtDescricaoProduto.setText("");
            txtNomeProduto.setText("");
            txtValorProduto.setText("");
            txtQuantidade.setText("");
            }
        }
    }//GEN-LAST:event_btnConfirmar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConfirmar1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagemBusca;
    private javax.swing.JTabbedPane pnlGuias;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtDescricaoProdutoAtualiza;
    private javax.swing.JTextField txtIdBusca;
    private javax.swing.JTextField txtNomeBusca;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeProdutoAtualiza;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidadeAtualiza;
    private javax.swing.JTextField txtValorMaxBusca;
    private javax.swing.JTextField txtValorMinBusca;
    private javax.swing.JTextField txtValorProduto;
    private javax.swing.JTextField txtValorProdutoAtualiza;
    // End of variables declaration//GEN-END:variables
}
