/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p.i;

import Modal.Funcionario;
import Modal.Login;
import dao.FuncionarioDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class TelaCadastroConsultaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroConsultaFuncionario
     */
    public TelaCadastroConsultaFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGuias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jdcData = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCPFBusca = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeEditar = new javax.swing.JTextField();
        txtCPFEditar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbSexoEditar = new javax.swing.JComboBox<>();
        jdcDataEditar = new com.toedter.calendar.JDateChooser();
        txtTelefoneEditar = new javax.swing.JFormattedTextField();
        txtEstadoEditar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtLoginEditar = new javax.swing.JTextField();
        txtSenhaEditar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome");

        txtNome.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNome.setName(""); // NOI18N
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFKeyTyped(evt);
            }
        });

        jLabel2.setText("CPF");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        cbSexo.setMaximumSize(new java.awt.Dimension(89, 22));
        cbSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbSexoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbSexoFocusLost(evt);
            }
        });

        jLabel4.setText("Sexo");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jdcData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdcDataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdcDataFocusLost(evt);
            }
        });
        jdcData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdcDataKeyTyped(evt);
            }
        });

        jLabel10.setText("Data de nascimento");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel8.setText("Telefone");

        jLabel6.setText("Estado");

        txtEstado.setMaximumSize(new java.awt.Dimension(64, 22));

        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel17.setText("Login");

        jLabel18.setText("Senha");

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogin)
                            .addComponent(cbSexo, 0, 142, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcData, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txtSenha))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pnlGuias.addTab("Cadastrar Funcionário", jPanel1);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsulta);

        jLabel3.setText("ID");

        jLabel5.setText("CPF");

        txtCPFBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFBuscaKeyTyped(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPFBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCPFBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlGuias.addTab("Consulta Funcionário", jPanel2);

        jLabel7.setText("Nome");

        txtNomeEditar.setMaximumSize(new java.awt.Dimension(64, 22));
        txtNomeEditar.setName(""); // NOI18N
        txtNomeEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeEditarFocusLost(evt);
            }
        });
        txtNomeEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeEditarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeEditarKeyTyped(evt);
            }
        });

        txtCPFEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFEditarFocusLost(evt);
            }
        });
        txtCPFEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFEditarKeyTyped(evt);
            }
        });

        jLabel9.setText("CPF");

        jLabel11.setText("Sexo");

        cbSexoEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outro" }));
        cbSexoEditar.setMaximumSize(new java.awt.Dimension(89, 22));
        cbSexoEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbSexoEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbSexoEditarFocusLost(evt);
            }
        });

        jdcDataEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jdcDataEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdcDataEditarFocusLost(evt);
            }
        });
        jdcDataEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdcDataEditarKeyTyped(evt);
            }
        });

        try {
            txtTelefoneEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneEditar.setMaximumSize(new java.awt.Dimension(64, 22));

        txtEstadoEditar.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel12.setText("Estado");

        jLabel13.setText("Telefone");

        jLabel14.setText("Data de nascimento");

        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel15.setText("Login");

        jLabel16.setText("Senha");

        jLabel19.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbSexoEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLoginEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefoneEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEstadoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcDataEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtSenhaEditar))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbSexoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtEstadoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefoneEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcDataEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLoginEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(jLabel16)
                    .addComponent(txtSenhaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pnlGuias.addTab("Alterar Funcionário", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String nome=txtNomeEditar.getText();
        String cpf=txtCPFEditar.getText();
        Date nascimento=jdcDataEditar.getDate();
        String sexo = cbSexoEditar.getSelectedItem().toString();
        String estado=txtEstadoEditar.getText();
        String telefone=txtTelefoneEditar.getText();
        String login=txtLoginEditar.getText();
        String senha=txtSenhaEditar.getText();

        if(nome.length()==0 || txtCPFEditar.getText().length()!=11 || jdcDataEditar.getDate()==null || sexo.equals("Selecione") || txtLoginEditar.getText().length()==0 || txtSenhaEditar.getText().length()<8){

            if(txtNomeEditar.getText().length()==0){
                txtNomeEditar.setBackground(Color.RED);
            }

            if(txtCPFEditar.getText().length()!=11){
                txtCPFEditar.setBackground(Color.RED);
            }

            if(jdcDataEditar.getDate()==null){
                jdcDataEditar.setBackground(Color.RED);
            }

            if(sexo.equals("Selecione")){
                cbSexoEditar.setBackground(Color.red);
            }
            
            if(txtLoginEditar.getText().length()==0){
                txtLoginEditar.setBackground(Color.red);
            }
            
            if(txtSenhaEditar.getText().length()<8){
                txtSenhaEditar.setBackground(Color.red);
                txtSenhaEditar.setText("Mínimo de 8 caractéres");
            }

        }else{
            jdcDataEditar.setBackground(Color.WHITE);

            Funcionario obj = new Funcionario (nome, sexo, estado, nascimento, telefone, cpf);
            int id = Integer.parseInt(lblId.getText());

            //Login obj = new Login(login, senha, id);
            
            boolean salvo= dao.FuncionarioDAO.Atualizar(id, obj);
            if(salvo){
                JOptionPane.showMessageDialog(this, "Funcionario editado com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
            
            

            txtCPFEditar.setText("");
            txtNomeEditar.setText("");
            txtEstadoEditar.setText("");
            txtNomeEditar.setText("");
            txtTelefone.setText("");
            txtLoginEditar.setText("");
            txtSenhaEditar.setText("");
            cbSexoEditar.setSelectedIndex(0);
            jdcDataEditar.setCalendar(null);
            
            lblId.setText("");
            

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void jdcDataEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcDataEditarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcDataEditarKeyTyped

    private void jdcDataEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataEditarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcDataEditarFocusLost

    private void jdcDataEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataEditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcDataEditarFocusGained

    private void cbSexoEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoEditarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoEditarFocusLost

    private void cbSexoEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoEditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoEditarFocusGained

    private void txtCPFEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFEditarKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtCPFEditar.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFEditarKeyTyped

    private void txtCPFEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFEditarFocusLost
        txtCPFEditar.setBackground(Color.yellow);
    }//GEN-LAST:event_txtCPFEditarFocusLost

    private void txtCPFEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFEditarFocusGained
        txtCPFEditar.setBackground(Color.white);
    }//GEN-LAST:event_txtCPFEditarFocusGained

    private void txtNomeEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEditarKeyTyped
        char c= evt.getKeyChar();

        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }

        if(txtNomeEditar.getText().length()>50){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeEditarKeyTyped

    private void txtNomeEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEditarKeyReleased
        txtNomeEditar.setText(txtNomeEditar.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeEditarKeyReleased

    private void txtNomeEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeEditarFocusLost
        txtNomeEditar.setBackground(Color.yellow);
    }//GEN-LAST:event_txtNomeEditarFocusLost

    private void txtNomeEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeEditarFocusGained
        txtNomeEditar.setBackground(Color.white);
    }//GEN-LAST:event_txtNomeEditarFocusGained

    private void txtCPFBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFBuscaKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtCPFBusca.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFBuscaKeyTyped

    private void jdcDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdcDataKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_jdcDataKeyTyped

    private void jdcDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataFocusLost
        jdcData.setBackground(Color.WHITE);
        UIManager.put("textHighlight", Color.WHITE);
        UIManager.put("textHighlightText", Color.RED);
        UIManager.put("control", Color.GREEN);
    }//GEN-LAST:event_jdcDataFocusLost

    private void jdcDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdcDataFocusGained
        jdcData.setBackground(Color.yellow);
    }//GEN-LAST:event_jdcDataFocusGained

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        String nome=txtNome.getText();
        String cpf=txtCPF.getText();
        Date nascimento=jdcData.getDate();
        String sexo = cbSexo.getSelectedItem().toString();
        String estado=txtEstado.getText();
        String telefone=txtTelefone.getText();
        String login=txtLogin.getText();
        String senha=txtSenha.getText();

        if(nome.length()==0 || txtCPF.getText().length()!=11 || jdcData.getDate()==null || sexo.equals("Selecione") || txtLogin.getText().length()==0 || txtSenha.getText().length()<8){
            lblMensagem.setForeground(Color.red);
            lblMensagem.setText("Por favor, preencha todos os campos mínimos necessários");

            if(txtNome.getText().length()==0){
                txtNome.setBackground(Color.RED);
            }

            if(txtCPF.getText().length()!=11){
                txtCPF.setBackground(Color.RED);
            }

            if(jdcData.getDate()==null){
                jdcData.setBackground(Color.RED);
            }

            if(sexo.equals("Selecione")){
                cbSexo.setBackground(Color.red);
            }
            
            if(txtLogin.getText().length()==0){
                txtLogin.setBackground(Color.red);
            }
            
            if(txtSenha.getText().length()<8){
                txtSenha.setBackground(Color.red);
                txtSenha.setText("Mínimo de 8 caractéres");
            }

        }else{
            jdcData.setBackground(Color.WHITE);
            lblMensagem.setForeground(Color.BLACK);
            lblMensagem.setText(" ");

            Funcionario obj = new Funcionario (nome, sexo, estado, nascimento, telefone, cpf);
            
            boolean salvo= dao.FuncionarioDAO.salvar(obj);
            if(salvo){
                JOptionPane.showMessageDialog(this, "Funcionario adicionado com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
            
            Funcionario id = dao.FuncionarioDAO.pegaId(cpf);
            
            int idFuncionario = (id.getID());
            
            Login objLogin = new Login(login, senha, idFuncionario);
            
            boolean salvologin= dao.LoginDAO.salvar(objLogin, idFuncionario);
            if(salvo){
                JOptionPane.showMessageDialog(this, "Login adicionado com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }

            txtCPF.setText("");
            txtNome.setText("");
            txtEstado.setText("");
            txtNome.setText("");
            txtTelefone.setText("");
            txtLogin.setText("");
            txtSenha.setText("");
            cbSexo.setSelectedIndex(0);
            jdcData.setCalendar(null);

        }
            
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        lblMensagem.setForeground(Color.BLACK);
        lblMensagem.setText(" ");

        txtCPF.setText("");
        txtNome.setText("");
        txtEstado.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        cbSexo.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoFocusLost
        cbSexo.setBackground(Color.white);
    }//GEN-LAST:event_cbSexoFocusLost

    private void cbSexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbSexoFocusGained
        cbSexo.setBackground(Color.yellow);
    }//GEN-LAST:event_cbSexoFocusGained

    private void txtCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyTyped
        char c= evt.getKeyChar();

        if( (c < '0' || c > '9')){
            evt.consume();
        }

        if(txtCPF.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCPFKeyTyped

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        txtCPF.setBackground(Color.white);
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setBackground(Color.yellow);
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped

        char c= evt.getKeyChar();

        if( (c == '0' || c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9')){
            evt.consume();
        }

        if(txtNome.getText().length()>50){
            evt.consume();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

        txtNome.setText(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        txtNome.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBackground(Color.YELLOW);
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setBackground(Color.yellow);
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        txtLogin.setBackground(Color.white);
    }//GEN-LAST:event_txtLoginFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setBackground(Color.yellow);
        if(txtSenha.getText().equals("Mínimo de 8 caractéres")){
            txtSenha.setText("");
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        txtSenha.setBackground(Color.white);
    }//GEN-LAST:event_txtSenhaFocusLost

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        String id = txtId.getText();
        String cpf = txtCPFBusca.getText();
        
        if(txtId.getText().length()==0 && txtCPF.getText().length()!=11){
            ArrayList<Funcionario> lista = dao.FuncionarioDAO.Listar();

            DefaultTableModel modelo = (DefaultTableModel)tblConsulta.getModel();
            modelo.setRowCount(0);
            for(Funcionario item : lista){
                modelo.addRow(new String[]{String.valueOf(item.getID()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getTelefone()) });
            }
        }else{
            if(txtId.getText().length()!=0 && txtCPF.getText().length()!=11){
                ArrayList<Funcionario> lista = dao.FuncionarioDAO.ListarId(id);

                DefaultTableModel modelo = (DefaultTableModel)tblConsulta.getModel();
                modelo.setRowCount(0);
                for(Funcionario item : lista){
                    modelo.addRow(new String[]{String.valueOf(item.getID()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getTelefone()) });
                }
            }else{
                if(txtId.getText().length()==0 && txtCPF.getText().length()==11){
                    ArrayList<Funcionario> lista = dao.FuncionarioDAO.ListarCPF(cpf);

                    DefaultTableModel modelo = (DefaultTableModel)tblConsulta.getModel();
                    modelo.setRowCount(0);
                    for(Funcionario item : lista){
                        modelo.addRow(new String[]{String.valueOf(item.getID()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getTelefone()) });
                    }
                }else{
                    ArrayList<Funcionario> lista = dao.FuncionarioDAO.Listar(id,cpf);

                    DefaultTableModel modelo = (DefaultTableModel)tblConsulta.getModel();
                    modelo.setRowCount(0);
                    for(Funcionario item : lista){
                        modelo.addRow(new String[]{String.valueOf(item.getID()), String.valueOf(item.getNome()), String.valueOf(item.getCpf()), String.valueOf(item.getTelefone()) });
                    }
                }
            }
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(tblConsulta.getSelectedRow()<0){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione um funcionario");
        }else{
            int linhaSelecionada = tblConsulta.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel)tblConsulta.getModel();

            int id = Integer.parseInt(tblConsulta.getValueAt(linhaSelecionada, 0).toString());
            boolean retorno = dao.FuncionarioDAO.excluir(id);   
            if(retorno){
                modelo.removeRow(linhaSelecionada);
                JOptionPane.showMessageDialog(rootPane, "Funcionario excluído com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao excluír");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        pnlGuias.setSelectedIndex(0);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblConsulta.getSelectedRow()<0){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione um funcionario");        }else{
            int linhaSelecionada = tblConsulta.getSelectedRow();

            String id = tblConsulta.getValueAt(linhaSelecionada, 0).toString();
            int ID =Integer.parseInt(id);

            ArrayList<Funcionario> lista = dao.FuncionarioDAO.ListaAlterar(ID);

            for(Funcionario item : lista){
                txtNomeEditar.setText(item.getNome());
                txtCPFEditar.setText(item.getCpf());
                //sexo
                txtEstadoEditar.setText(item.getEstado());
                txtTelefoneEditar.setText(item.getTelefone());
                //EstadoCivil
                jdcDataEditar.setDate(item.getDataNascimento());
            }

            lblId.setText(id);
            pnlGuias.setSelectedIndex(2);
       }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroConsultaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JComboBox<String> cbSexoEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcData;
    private com.toedter.calendar.JDateChooser jdcDataEditar;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTabbedPane pnlGuias;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFBusca;
    private javax.swing.JTextField txtCPFEditar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoEditar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtLoginEditar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEditar;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenhaEditar;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefoneEditar;
    // End of variables declaration//GEN-END:variables
}
